version: "2"

services:

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./conf/site.conf:/etc/nginx/conf.d/site.conf
      - ./www:/var/www

####### php 5.6 без xdebug
#  php:
#    build: ./php56
#    container_name: php
#    restart: always
##    command:
##      - docker cp ../bitrix_biz_v15.0.6_modules/bx_demo/. php:/var/www
#    volumes:
#      - ./www:/var/www

####### php 5.6 c xdebug
#  php:
#    build: ./php56_xdebug # https://habr.com/ru/post/712670/
#    container_name: php
#    restart: unless-stopped
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    #    command:
#    #      - docker cp ../bitrix_biz_v15.0.6_modules/bx_demo/. php:/var/www
#    volumes:
#      - ./www:/var/www

####### php 7.4 без xdebug
  php:
    build: ./php7.4
    container_name: php
    restart: unless-stopped
    volumes:
      - ./www:/var/www
#  php:
#    build: ./php8.2
#    container_name: php
#    restart: unless-stopped
#    volumes:
#      - ./www:/var/www

#  mariadb:
#    #    image: mariadb:10.2
#    image: mysql
#    #    container_name: mariadb
#    container_name: mariadb
#    environment:
#      MYSQL_ROOT_PASSWORD: 1234567890
#      MYSQL_DATABASE: tevex_mehnik
#      MYSQL_USER: tevex_mehnik
#      MYSQL_PASSWORD: CvnT3TJecz
#    command: mysqld --sql-mode="" --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
#    restart: unless-stopped

#  gateway_db:
#    container_name: gateway_db
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_USER: ${PG_USER}
#      POSTGRES_PASSWORD: ${PG_PASSWORD}
#      POSTGRES_DB: ${PG_DB}
#      TZ: Europe/Moscow
#      PGTZ: Europe/Moscow
##    volumes:
##      - "./db:/var/lib/postgresql/data:rw"
#    ports:
#      - "127.0.0.1:5432:5432"
#
#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
#      PGADMIN_LISTEN_PORT: 5454
#    ports:
#      - 5454:5454/tcp

  mysql:
#    image: mariadb:10.2
    image: mysql
#    container_name: mariadb
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: test
#      MYSQL_USER: test
#      MYSQL_PASSWORD: 123
    command: mysqld --sql-mode="" --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: unless-stopped

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=4096M